-- BORRAR LA TABLA TEMPORAL SI YA EXISTE
DROP TABLE IF EXISTS #temp_Employee

-- VER LA ESTRUCTURA DE UNA TABLA
EXEC SP_COLUMNS usuarios;

-- VER LAS TABLAS EXISTENTES CREADAS
EXEC SP_TABLES @TABLE_OWNER = 'DBO';
